# GitHub Actions - Check date last commit
# Vérifie 2 fois par mois (le 1er et le 15 du mois) que la date du dernier commit du répertoire spécifié
# ne dépasse pas le nombre de mois configuré.
# Le repos doit être en public

name: Check date last commit

on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    env:
    
      # Répertoire (ou fichier) du repos à vérifier
      LAST_COMMIT_PATH: src
      
      # Le nombre de mois à ne pas dépasser pour le dernier commit
      DATE_MONTH_LIMIT: 6
      
    steps:
     - name: Check date
       run: |
        date="$(curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits?path=$LAST_COMMIT_PATH'&'per_page=1 | jq '.[0]' | jq -r '.commit.author.date')"
        timestamp=$(date --utc -d "$date" +%s)
        limit=$(date -d "-$DATE_MONTH_LIMIT month" +%s)
        if [ $timestamp -lt $limit ]; then
          exit 1
        fi
